[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/cpb",
]
default-members = ["crates/cpb"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Marcel"]
license = "MIT OR Apache-2.0"

[profile.release]
debug = 2
lto = true
opt-level = "s"

[profile.dev]
opt-level = 1
